#!/bin/sh

rfkill unblock bluetooth

echo "Powering the adaptater…"
if [[ $1 == 'hard' ]]
then
    killall blueman-manager
    sudo systemctl stop bluetooth
    sleep .2
    sudo systemctl restart bluetooth

    while [[ $(echo -e "select 8C:68:8B:61:0C:51\n" | bluetoothctl | grep '0C:51 not available') ]];
    do

        echo "unblocking bluetooth…"
        rfkill block bluetooth
        sleep .1
        rfkill unblock bluetooth
        sleep .1

        echo "modprobe restart btusb…"
        sudo /usr/bin/modprobe -r btusb
        sleep .1
        sudo /usr/bin/modprobe btusb
        sleep 1.1

        echo "restart bluetooth…"
        sudo systemctl restart bluetooth
        #systemctl --no-pager status bluetooth
        sleep .5

    done

fi


sleep 0.1

# selecting the external device, power it on, connect to headset
echo "Trying to pair…"
echo -e "select 8C:68:8B:61:0C:51\npower on\nconnect E4:22:A5:30:67:BF\n" | bluetoothctl
if [[ $1 == 'hard' ]]
then
    while [[ $(echo -e "select 8C:68:8B:61:0C:51\npower on\nconnect E4:22:A5:30:67:BF\n" | bluetoothctl | grep 'Échec') ]];
    do
        echo "pairing…"
        sleep 2
        if [[ $(($RANDOM%10)) == 0 ]];
        then
            break
        fi
    done
fi

blueman-manager &
# bluetoothctl connect E4:22:A5:30:67:BF

sleep 1
setxkbmap fr bepoz

# change latency to 30ms (to avoid stuttering)
pactl set-port-latency-offset bluez_card.E4_22_A5_30_67_BF headset-output 50000

sleep 5
setxkbmap fr bepoz
