#!/usr/bin/env python3
"""Print without newline the current date"""

import datetime
import argparse

ACTIONS = 'datetime', 'date', 'time'
STYLES = {
    'compact': {
        'date': "%y%m%d",
        'time': "%H:%M",
        'datetime': "%y%m%d-%H:%M",
    },
    'full': {
        'date': "%Y-%m-%d",
        'time': "%H:%M",
        'datetime': "%Y-%m-%d_%H:%M",
    },
    'human': {
        'date': "%y/%m/%d",
        'time': "%Hh%Mm",
        'datetime': "%y/%m/%d-%Hh%Mm",
    }
}

def parse_cli():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=ACTIONS, type=str, help="what to print", default=ACTIONS[0])
    parser.add_argument('style', choices=tuple(STYLES), type=str, help="how to print", default=tuple(STYLES)[0])
    parser.add_argument('--yesterday', action='store_true', help="provide date for yesterday, not today")
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_cli()
    now = datetime.datetime.now()
    if args.yesterday:
        now -= datetime.timedelta(days=1)
    print(now.strftime(STYLES[args.style][args.action]), flush=True, end='')
